mindmap
  root((OSINT Intelligence Tools))
    (Plataformas Integradas)
      (Maltego)
        (Análisis de Relaciones)
        (Transformaciones)
        (Visualización de Datos)
      (The_Spy_Job)
        (Reconocimiento)
        (Análisis de Información)
        (Recopilación de Datos)
    
    (Análisis de Personas)
      (Búsqueda de Usuarios)
        (Sherlock)
        (WhatsMyName)
        (UserRecon)
        (NameCheckup)
      (Análisis de Números)
        (TrueCaller)
        (PhoneInfoga)
        (Sync.ME)
        (NumLookup)
        (FakeSms)
    
    (Análisis Digital)
      (Correo Electrónico)
        (Hunter.io)
        (Email-Format)
        (Epieos)
        (Email Finder)
      (Redes Sociales)
        (Análisis General)
          (Social Analyzer)
          (Social Searcher)
          (GeoSocial Footprint)
        (Herramientas Específicas)
          (Instagram)
            (Instaloader)
            (Instapy)
          (Twitter)
            (Twint)
